"use client";
import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { HeaderClient } from "@/components";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { saira } from "@/utils/ChangeFont";
import { PrimeReactProvider } from "primereact/api";
import {
  ItemContextProvider,
  MainContextProvider,
  SearchContextProvider,
} from "@/contexts";

const client = new QueryClient();
const metadata: Metadata = {
  title: "Meu Restaurante",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      {
        <MainContextProvider>
          <ItemContextProvider>
            <SearchContextProvider>
              <QueryClientProvider client={client}>
                <PrimeReactProvider>
                  <body className={saira.className}>
                    <HeaderClient />
                    {children}
                  </body>
                </PrimeReactProvider>
              </QueryClientProvider>
            </SearchContextProvider>
          </ItemContextProvider>
        </MainContextProvider>
      }
    </html>
  );
}
