"use client";
import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { HeaderClient } from "@/components";
import { saira } from "@/utils/ChangeFont";

const metadata: Metadata = {
  title: "Meu Restaurante",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <div>
      <div className={saira.className}>
        <HeaderClient />
        {children}
      </div>
    </div>
  );
}
