import type { Metadata } from 'next'
import { Saira_Condensed } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'

const saira = Saira_Condensed({weight:["400"], subsets:['latin']})

export const metadata: Metadata = {
  title: 'Meu Restaurante',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>{children}</body>
    </html>
  )
}
