import type { Metadata } from "next";
import { Permanent_Marker } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { Header } from "@/components";

const saira = Permanent_Marker({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meu Restaurante",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={`${saira.className} w-full h-fit flex justify-between flex-col `}>
        <Header />
        <div className="">
          {children}
        </div>
      </body>
    </html>
  );
}
